export const GET_PAGE_REQUEST = 'GET_PAGE_REQUEST';
export const SET_CONTENT = 'SET_CONTENT';
export const GET_NAV_DATE = 'GET_NAV_DATE';
export const SET_NAV_CONTENT = 'SET_NAV_CONTENT';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';